[package]
name = "minif2f"
version = "0.1"
lean_version = "leanprover-community/lean:3.30.0"
path = "lean/src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "1d4990e262a82ed7d30a1c5b63e428df71839718"}
