[package]
name = "minif2f"
version = "1.0"
lean_version = "leanprover-community/lean:3.39.1"
path = "lean/src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "b72300f3455ae73c3ab9ed40fc1f80bbb9c85ba4"}
